### ISSUE TITLE
How to handle require.js in v2.0 ?

### ISSUE THREAD

**Issue by sleeper** [yeoman/grunt-usemin#112]
In the scope of usemin 2.0, I'm rewriting part of `grunt-usemin` ... One question that keeps bothering me is how to handle `require.js`.

Actually `require.js` is installed by bower in `app/components/requirejs/require.js`, but then how to handle it:
1. Have it go through the standard flow (`concat` -> `uglifyjs`), and have it concatenated to other files
2. Add it to the `copy` target, and copied to `scripts/vendor/require.js`

I would tend to say that 2 is better but would really like to ear from you (also taking into account I do not know `require.js` vey well).

**Comment by lauradaniela** [comment]
@DanielTate you can resolve the error?

**Comment by DanielTate** [comment]
@lauradaniela No I am no longer using usemin
