### ISSUE TITLE
Please add HTML img tag processing to usemin

### ISSUE THREAD

**Issue by geoffsdavis** [yeoman/grunt-usemin#127]
It would be great if usemin also had the ability to handle revved images (gif/jpg/png) that are referenced through HTML img tags. Any plans on this?

**Comment by dchacke** [comment]
A little late to the party, but @robwierzbowski's comment helped me out because I needed to make the following change:

```javascript
usemin: {
  // html: ['<%= yeoman.dist %>/{,*/}*.html'],
  html: ['<%= yeoman.dist %>/{,*/**}*.html'],
  css: ['<%= yeoman.dist %>/styles/{,*/}*.css'],
  options: {
    assetsDirs: [
      '<%= yeoman.dist %>',
      '<%= yeoman.dist %>/images',
      '<%= yeoman.dist %>/styles'
    ]
  }
}
```

I came here from Google because my img src tag weren't updated correctly when building the project, just in case anyone else has the same issue.
