### ISSUE TITLE
New build type to remove html blocks

### ISSUE THREAD

**Issue by sym3tri** [yeoman/grunt-usemin#128]
It would be nice to conditionally remove some script tags or blocks of html. For example if using live-reload or development specific JS or CSS. Maybe something like this:

```
<body>
...
  <!-- build:remove -->
  <script src="dev/only/script.js"></script>
  <!-- endbuild -->
</body>
```

**Comment by sdanielspq** [comment]
No undefined in index html file, but template handlebars file had undefined text
