### ISSUE TITLE
Multiple Destinations in useminPrepare

### ISSUE THREAD

**Issue by iamkevingreen** [yeoman/grunt-usemin#157]
I am new to grunt, but trying my hardest to figure things out and just hit a wall with useminPrepare. 

I have 2 distribution directories, the standard 'dist' and another 'dist2' (for another group of files using the same style/js)

The reason for this is so i can serve two different groups of files to two different git repos for separate teams to handle. My issue is that useminPrepare only appears to let me set one destination for handling the blocks in my html files.

``` javascript
useminPrepare: {
            html: 'src/templates/layouts/*.html',
            options: {
                dest: 'dist'
            }
        },
```

I tried ['dist', 'dist2'] I tried creating sub methods like dist: { options: {dest 'dist'}} and calling them in my build commands but no luck. 

Does anyone have experience doing this or have a better suggestion? I am still new to all this but really trying to convert my life to this workflow and this particular issue is driving me nuts.

**Comment by dudewad** [comment]
+1

**Comment by AlessandroGurgel** [comment]
+1

**Comment by lidia-freitas** [comment]
+1

**Comment by GitRubb** [comment]
+1

**Comment by keatz55** [comment]
+1
