### ISSUE TITLE
grunt-usemin is not replacing image file paths for Angular Responsive Images <img> attribute

### ISSUE THREAD

**Issue by siddhion** [yeoman/grunt-usemin#164]
I am using Angular Responsive Images which is an AngularJS directive for handling responsive images. 
https://github.com/c0bra/angular-responsive-images
An example of markup using it looks like this:

```
<img src="/images/320/d22d76a9.lounge_coffee-320.jpg" ng-src-responsive="[ [ '(min-width: 480px)', '/images/480/lounge_coffee-480.jpg' ], [ '(min-width: 660px)', '/images/660/lounge_coffee-660.jpg' ], [ '(min-width: 770px)', '/images/770/lounge_coffee-770.jpg' ], [ '(min-width: 990px)', '/images/990/lounge_coffee-990.jpg' ] ]">
```

It turns out that `usemin` is only looking for image file paths that are defined in the `<img>` element's `src` attribute but are ignoring all image paths defined in the `ng-src-responsive` attribute. How can I make `usemin` also look for the `ng-src-responsive` attribute?

My Gruntfile.js usemin settings are fine. I need to dig into the `usemin` code I believe.

```
usemin: {
      html: ['<%= yeoman.dist %>/**/*.html'],
      css: ['<%= yeoman.dist %>/styles/**/*.css'],
      options: {
        dirs: ['<%= yeoman.dist %>']
      }
    },
```

**Comment by vinaygopinath** [comment]
I just ran into this issue while using [md-icon](https://material.angularjs.org/#/demo/material.components.button), one of the Angular material directives. I would imagine that this is going to be increasingly common problem given the soup of custom directives floating around. A more accessible way of making grunt-usemin look for image references would be nice.

For those facing similar issues,  @siddhion's solution above works fine, but the relevant file is now `node_modules/grunt-usemin/lib/fileprocessor.js`

**Comment by robert-malai** [comment]
I found out that one can extend the patterns of the HTML files in the project's gruntfile, which I find to be a much nicer way to handle custom directives.
```javascript
patterns: {
  html: [
    [
      /<your-directive-name-here[^\>]*[^\>\S]+custom-src-attribute-here=['"]([^'"\)#]+)(#.+)?["']/gm,
      'Update the HTML with the new asn-editable-picture filenames'
    ]
  ],
  js: [
    [
      /(images\/.*?\.(?:gif|jpeg|jpg|png|webp))/gm,
      'Update the JS to reference our revved images'
    ]
  ]
}
```

**Comment by ctrom** [comment]
As mentioned by @vinaygopinath, this issue applies to `<md-icon>` elements in addition to `<img>` elements that make use of the `ng-src-responsive` source attribute that @siddhion noted in the original post. I'm sure there are other instances with the same issue. This is a bug that as of v3.1.1 has not been addressed.

**Comment by jimdowling** [comment]
I still have this issue with <md-icon>. @robert-malai  - i couldn't get your solution working. I tried reading about how/where to configure tasks in the Gruntfile to extend the html patterns. But couldn't get it working. @robert-malai Could you please indicate where to add your fix in the Gruntfile?

**Comment by robert-malai** [comment]
@jimdowling this is the whole content of my Grunt.js file:
https://gist.github.com/robert-malai/edbad628593af55aeb107f8c8d44c498

**Comment by jimdowling** [comment]
@robert-malai  cheers!
