### ISSUE TITLE
V2: require.js blocks are no more supported

### ISSUE THREAD

**Issue by jarrodpayne** [yeoman/grunt-usemin#172]
Could someone please explain. In `usemin.js` there is a line causing this that basically says, if the script block has "data-main", throw error.

What's the new way to get going with this. I'm using v2 with PR #162 for **multiple target** support in my Yeoman project.

```
Running "useminPrepare:dist" (useminPrepare) task
Going through app/index.html to update the config
Looking for build script HTML comment blocks
Fatal error: require.js blocks are no more supported.
```

**Comment by lauradaniela** [comment]
@jpdesigndev how you can resolve the problem?
