### ISSUE TITLE
How to use csso for cssmin?

### ISSUE THREAD

**Issue by wzxu** [yeoman/grunt-usemin#189]
Hey there. I'm just starting to explore Yeoman. Today I generated a webapp, was just poking around and decided to replace cssmin with csso.

I installed grunt-csso, replaced cssmin with csso in the "build" task, and according to README I put `cssmin: 'csso'` into usemin's options. However, when I ran grunt, it complained no "csso" targets found, meaning that it's not configured. If I manually copy-n-paste cssmin's commented-out backup settings to csso in the Gruntfile, it works flawlessly. 

Am I doing something wrong here? Thanks!

**Comment by oller** [comment]
Did you get anywhere with this @wzxu, am encountering the same problem of trying to use the csso minifying engine alongside usemin
