### ISSUE TITLE
Concat is harmful for your CSS?

### ISSUE THREAD

**Issue by eirslett** [yeoman/grunt-usemin#225]
The problem with running concat before cssmin, is that all relative file information is lost during the concat step.

if the file `foo/bar.css` has a property `background-image: url('hello.png')` and we concatenate it to `bar.min.css`, the url should in the concatenated version be resolved to `foo/hello.png`, but the logic to make that happen doesn't exist in concat. The problem is the same with `@import` statements (#201).

I believe the only way to properly fix this, is to rewrite the css flow from using concat to only [using cssmin with support for relative urls](https://github.com/gruntjs/grunt-contrib-cssmin/issues/38). Or am I completely wrong?

**Comment by nickcmaynard** [comment]
FWIW, I managed to fix this using @jitowix's suggestion, but updated for my specific use case:
```js
useminPrepare: {
  html: '<%= appRoot %>/common/index.html',
  options: {
    dest: '<%= appRoot %>/common/dist',
    flow: {
      steps: {
        js: ['concat', 'uglifyjs'],
        css: ['cssmin']
      },
      post: {
        css: [{
          name: 'cssmin',
          createConfig: function (context, block) {
            var generated = context.options.generated;
            generated.options = {
              sourceMap: true, // turn on sourcemaps too
              rebase: true // defaults to false for some unfathomable reason
            };
          }
        }]
      }
    }

  }
}
```
