### ISSUE TITLE
usemin not replacing image names in javascript files

### ISSUE THREAD

**Issue by doomsbuster** [yeoman/grunt-usemin#235]
Configuring JS key and its patterns in the grunt file, but the usemin task does not replace the compressed image name in the uglified script file in the dist/scripts directory. My optimized images are in dist/images directory. Here is the gist containing my Gruntfile.js and minified script file.
https://gist.github.com/doomsbuster/7507710

**Comment by m0ngr31** [comment]
@mcrocksteady Thanks, that solved a problem I was having.

**Comment by uriannrima** [comment]
For those who might need it for some situation like me, here's a small snippet to make it replace *.html files inside the javascript. We needed to change templateUrls from angularjs with rev files:

```
patterns: {
  js: [
	[/((scripts|views)\/.*?\.html)/gm, 'Update the JS to reference our revved htmls']
  ]
}
```

**Comment by ramsathees** [comment]
I am using Angular ui-grid. Inside js file i am loading my image file it is working fine in my local . After converting my js file into min.js . My image is not loaded . please help me out from this problem.
i have attached my grunt js file code here.
`  filerev: {
      dist: {
        src: [
          '<%= yeoman.dist %>/scripts/{,*/}*.js',
          '<%= yeoman.dist %>/styles/{,*/}*.css',
          '<%= yeoman.dist %>/images/{,*/}*.{png,jpg,jpeg,gif,webp,svg}',
          '!<%= yeoman.dist %>/images/no-filerev/{,*/}*.{png,jpg,jpeg,gif,webp,svg}',
          '<%= yeoman.dist %>/styles/fonts/*'
        ]
      }
    },

    // Reads HTML for usemin blocks to enable smart builds that automatically
    // concat, minify and revision files. Creates configurations in memory so
    // additional tasks can operate on them
    useminPrepare: {
      html: '<%= yeoman.app %>/index.html',
      options: {
        dest: '<%= yeoman.dist %>',
        flow: {
          html: {
            steps: {
              js: ['concat'],
              css: ['cssmin']
            },
            post: {}
          }
        }
      }
    },
    
    //url rewrite in css files under dist
    cssUrlRewrite: {
        dist: {
          src: '<%= yeoman.dist %>/styles/main.css',
          dest: '<%= yeoman.dist %>/styles/main.css',
          options: {
            skipExternal: true,
            rewriteUrl: function(url, options, dataURI) {
              grunt.log.write('url>>>>>>>>'+url);
              //grunt.log.write('options>>>>>>>>'+options.baseDir);
              //grunt.log.write('dataURI>>>>>>>>'+dataURI);
              var path;
              if(url.indexOf('app/')>=0)
              path = url.replace('app/styles/', '');
              if(url.indexOf('dist/')>=0)
              path = url.replace('dist/styles/', '');
              
            grunt.log.write('path>>>>>>>>'+path);
              //var hash = require('crypto').createHash('md5').update(dataURI).digest('hex');
            grunt.log.write('updated path>>>>>>>>'+ path);
              return path;
            }
          }
        }
      },

    // Performs rewrites based on filerev and the useminPrepare configuration
    usemin: {
      html: ['<%= yeoman.dist %>/{,*/}*.html'],
      css: ['<%= yeoman.dist %>/styles/{,*/}*.css'],
      options: {
        assetsDirs: [
          '<%= yeoman.dist %>',
          '<%= yeoman.dist %>/images',
          '<%= yeoman.dist %>/styles',
		  '<%= yeoman.dist %>/scripts'
		  
        ],
		patterns: {
          // FIXME While usemin won't have full support for revved files we have to put all references manually here
          html: [
              [/(images\/.*?\.(?:gif|jpeg|jpg|png|webp|svg))/gm, 'Update the JS to reference our revved images'],
			    [/(scripts\/.*?\.(?:js))/gm, 'Update the JS to reference our revved images'],
				  [/(styles\/.*?\.(?:css))/gm, 'Update the JS to reference our revved images']
          ]
      }
      }
    },
 uglify: {
      dist: {
        files: {
          '<%= yeoman.dist %>/scripts/scripts.js': [
            '<%= yeoman.dist %>/scripts/scripts.js'
          ],
          '<%= yeoman.dist %>/scripts/vendor.js': [
            '<%= yeoman.dist %>/scripts/vendor.js'
          ]
        }
      }
    },
    // concat: {
    //   dist: {}
    // },

    imagemin: {
      dist: {
        files: [{
          expand: true,
          cwd: '<%= yeoman.app %>/images',
          src: '{,*/}*.{png,jpg,jpeg,gif}',
          dest: '<%= yeoman.dist %>/images'
        }]
      }
    },

    svgmin: {
      dist: {
        files: [{
          expand: true,
          cwd: '<%= yeoman.app %>/images',
          src: '{,*/}*.svg',
          dest: '<%= yeoman.dist %>/images'
        }]
      }
    },
`
