### ISSUE TITLE
Uglify failing when removed from flow -> steps

### ISSUE THREAD

**Issue by kartikluke** [yeoman/grunt-usemin#332]
No "uglify" targets found.
Warning: Task "uglify" failed. Use --force to continue.

```
useminPrepare: {
      html: '<%= yeoman.app %>/index.html',
      options: {
        dest: '<%= yeoman.dist %>',
        flow: {
          steps: {'js' : ['concat'], 'css': ['concat', 'cssmin']},
          post: {}
        }
    }
 },
```

I'm able to run it using --force but is there a way for uglifyjs block to not be created/run?

**Comment by stephanebachelier** [comment]
Should be fixed by #520

**Comment by benliu723** [comment]
@Tomino2112 Thanks a lot for your comment, it fix my issue.

**Comment by stephanebachelier** [comment]
closing as fixed in master
