### ISSUE TITLE
Usemin ignore useminPrepare Blocks if the file contain wrong newline character.

### ISSUE THREAD

**Issue by kymmt** [yeoman/grunt-usemin#365]
if the file contains LF and CRLF characters, usemin does not do anything.
i think this should raise error or remove characters.

**Comment by rahulbpatel** [comment]
FYI... ran into the same issue.  Ended up using @sindresorhus' [grunt-lineending](https://github.com/suisho/grunt-lineending) plugin before my useminPrepare task to consolidate line endings.  Thanks @sindresorhus!
