### ISSUE TITLE
How to use with grunt-contrib-requirejs?

### ISSUE THREAD

**Issue by fenduru** [yeoman/grunt-usemin#370]
#112 seems to have questions left unanswered. The one I'm particularly interested in is how to use usemin to handle:

``` html
<!-- build:js dist/my-compiled-source.js -->
<script data-main"src/uncompiled-main.js" src="bower_components/requirejs/require.js"></script>
<!-- endbuild -->
```

This seems like a very straightforward use case that should be supported. In development, I want to lazily load my source files without requirejs:compile. When I build, I want to strip that out, and instead use the r.js compiled js.

I get the "Warning: require.js blocks are no more supported" message, but I don't understand why what I am trying to do has any effect on usemin.

**Comment by justin-calleja** [comment]
Was an SO question ever created? And is [this](https://github.com/yeoman/grunt-usemin/issues/112#issuecomment-38138959) workaround still the suggested solution?
