### ISSUE TITLE
usemin not updating  <object> tag to revved filename of SVG

### ISSUE THREAD

**Issue by mmjmanders** [yeoman/grunt-usemin#401]
I'm using an SVG image in my html with PNG fallback. The correct way to do this is:

``` html
<object type="image/svg+xml" data="images/logo.svg">
  <img src="images/logo.png" alt="Logo"/>
</object>
```

The files both get revved and get filenames like `logo.7e31c23a.svg` and `logo.2ee29cbf.png`. But in the minified HTML output in the `dist` folder this piece of HTML becomes:

``` html
<object type="image/svg+xml" data="images/logo.svg">
  <img src="images/logo.2ee29cbf.png" alt="Logo">
</object>
```

The SVG it tries to load cannot be found.

**Comment by leobudima** [comment]
+1

**Comment by lanfear** [comment]
+1
