### ISSUE TITLE
Add support for grunt-contrib-compress

### ISSUE THREAD

**Issue by danemacaulay** [yeoman/grunt-usemin#405]
I can understand that this might not be wanted, its the web servers responsibility to serve up gzipped content if the client supports it. Its a nice step to add in to the build process and easy to add to the project.

The `lib/config/uglifyjs.js` generator has everything a `lib/config/compress.js` generator would need short of a name change. One just has to be sure to set the usemin blocks filename to use the `.gz` extension as compress tacks this on the end by default.

``` html
<!-- build:js js/vendor.min.js.gz-->
```

Some simple middleware for testing these assets with connect:

``` js
function(req, res, next) {
  if ((/\.gz/).test(req.url)) {
    res.setHeader('Content-Encoding', 'gzip');
  }
  next();
}
```

This does tie your hands with the `.gz` extension which might break on older browsers

**Comment by guy-mograbi-at-gigaspaces** [comment]
+1 s3 me too.

**Comment by BelfordZ** [comment]
:+1: there is curently no other way to gzip if you are hosting via s3 / cloudfront. 

I am doing it outside of usemin right now, but it would be nicer to have it work
