### ISSUE TITLE
Url encoded characters are not decoded

### ISSUE THREAD

**Issue by fcamblor** [yeoman/grunt-usemin#417]
I have an image with spaces inside it (boooh, it's bad ;-))
`images/foo bar.png`

I'm `rev`-ing during my `grunt` build, this is transformed to something like
`images/c4feb4b3.foo bar.png`

I reference this image in an html `img` tag, with encoded url path :
`<img src="images/foo%20bar.png" />`

When `usemin:html` task is executed, my html image is not updated because, I think, `images/foo%20bar.png` !== `images/foo bar.png`

Simple workaround is to change my html to :
`<img src="images/foo bar.png" />` and it worked like a charm.

Just wanted to share the issue which is not a big issue at all :-)

**Comment by stephanebachelier** [comment]
@fcamblor we do not always have filename without spaces or accentuated characters. Not everyone knows this rules.

Tagged as doc it should be useful for others users.

But also a question, do we need to support url encoded characters ? IMO this is the work of browsers and your source file should use space if your path have spaces.

**Comment by fcamblor** [comment]
Agree, there is an easy workaround so I don't think supporting encoded characters un grunt-usemin is required
