### ISSUE TITLE
Multiple flows in useminPrepare and multiple targets in usemin

### ISSUE THREAD

**Issue by reda-alaoui** [yeoman/grunt-usemin#420]
Hi,

I have the following project organization for an angular application:

app
-- scripts
-- styles
-- views
-- index.html

I sucessfully output two concatenated and uglyfied script file in my dist folder.

What I need now is to also generate a copy of index.html, named index-debug.html that references the concatenated but not uglified script files to be able to debug the javascript code in production.

I want to obtain:

dist
-- scripts
-- scripts-debug
-- styles
-- views
-- index-debug.html

I think that I should use multple flows and targets to succeed.
But I don't know how to define multiple flows in useminPrepare and then use them with multiple targets in usemin.

**Comment by stephanebachelier** [comment]
Duplicate of #456 and #487
