### ISSUE TITLE
Image tags set to draggable="false" are rewritten to 'draggable' - big bug

### ISSUE THREAD

**Issue by stereokai** [yeoman/grunt-usemin#427]
A breaking bug:

Image tags like the one below:
`<img class="...." src="..." draggable="false">`

Become like this after build:
`<img class="...." src="..." draggable>`

I'm not sure if this bug occurs in `filerev` or in `usemin`, so I posted this on both repos.
https://github.com/yeoman/grunt-filerev/issues/42

**Comment by stephanebachelier** [comment]
As stated before this should not be an issue with usemin, but with an HTML minifier.

Feel free to reopen if it's still related to usemin.
