### ISSUE TITLE
Task only replacing image references in <img> tags

### ISSUE THREAD

**Issue by mrowles** [yeoman/grunt-usemin#428]
Hi,

Is there anyway to force usemin/rev to update all occurrences of an updated image outside of the <img src> replacements:

````html
<!-- This has been updated -->
<img src="images/b1kajsmf.main.jpg" />

<picture>

    <!-- This was not updated -->
    <source srcset="images/main.jpg" media="(min-width: 1200px)" />
    <source srcset="images/main-lg.jpg" media="(min-width: 992px)" />
    <source srcset="images/main-md.jpg" media="(min-width: 768px)" />
    <source srcset="images/main-sm.jpg" media="(min-width: 1px)" />

    <!-- This was not updated -->
    <img srcset="images/main.jpg" alt="Epic punting">

</picture>
````

I don't know if this is doable with blocks, especially since I have those media attributes in the <source> elements.

Thanks,
Matt

**Comment by stephanebachelier** [comment]
@mrowles is your use case supported by current version of usemin ? 

@aendrew PR to support single srcset has been merged. It doesn't support multiple inline srcset as reference in #458 but your use case should be covered, unless Im wrong.

**Comment by aendrew** [comment]
@stephanebachelier Yep, though it's really a hack-level improvement. Being able to specify multiple srcset items is a key aspect of that standard. I'm happy with just `@2x` for now, though...

**Comment by mrowles** [comment]
@stephanebachelier I updated to the latest version of usemin (node 10.3.2), and tested with the code from my initial comment and it works great, thanks all :+1:

**Comment by stephanebachelier** [comment]
@aendrew, you're right about hack-level improvement, but it will helps users for now. A better solution will be done in #458, but I would wait for HTML parser work to be done before going on this.
