### ISSUE TITLE
angular + usemin : removing attributes from stylesheet

### ISSUE THREAD

**Issue by vineshhpatel** [yeoman/grunt-usemin#431]
I use following code :

`
<link href="./css/base-style.css" rel="stylesheet" ng-if="someCondition">
`

This block of code is replaced by 

`<link rel="stylesheet" href="css/base-style.css">`

is there any way to keep ng-if in output?

**Comment by yaojingguo** [comment]
Why not usemin leave html element attributes it does not recognize? For my case, it removes thymeleaf stuff:

```
<!-- build:js js/all.js -->
<script src="../../../../js/utils.js" th:src="@{/js/utils.js}"></script>
<!-- endbuild -->
```
