### ISSUE TITLE
Throw up on missing HTML?

### ISSUE THREAD

**Issue by ain** [yeoman/grunt-usemin#452]
I've just spent quite a lot of time understanding what's going on because the preceding `copy:dist` task did not output HTML for `usemin` to work on and `usemin` just fell through silently:
```sh
Running "usemin:html" (usemin) task

Done, without errors.
```
I'd suggest `usemin` throwing up on a target that is not there (at all).

I realise there could be a glob pattern involved, but could we do anything to aid the user towards the issue?

**Comment by arthurvr** [comment]
Duplicate of https://github.com/yeoman/grunt-usemin/issues/494, isn't it?

**Comment by ain** [comment]
No. #494 is a dupe of this one.

**Comment by arthurvr** [comment]
Whoops. Right. Can one close that ticket?

**Comment by stephanebachelier** [comment]
@arthurvr which one do you want to close ?

**Comment by stephanebachelier** [comment]
@arthurvr closed #494 in favor of this one

**Comment by stephanebachelier** [comment]
By the way it should be resolved by #306, but this PR need to be updated as it is too old now.

**Comment by stephanebachelier** [comment]
Fixed in `dev` branch
