### ISSUE TITLE
Trying to override css and js blockReplacements - not working?

### ISSUE THREAD

**Issue by trludewig** [yeoman/grunt-usemin#471]
I am guessing this is user error on my part.  But could someone take a look at this?  I want to replace the css and js includes with custom text, not the out-of-the-box.  Here is a snippet from my Grunt file.

```
   useminPrepare: {
        html: ['<%= appConfig.dist %>/{,*/}*.html', '<%= appConfig.dist %>/{,*/}*.page'],
        options: {}
    },

    // Performs rewrites based on filerev and the useminPrepare configuration
    usemin: {
        html: ['<%= appConfig.dist %>/{,*/}*.html', '<%= appConfig.dist %>/{,*/}*.page'],
        options: {
            blockReplacements: {
                css: function (block) {
                    grunt.log.writeln('in css block!');
                    return '<link href="{!URLFOR($Resource.SCSClientView, \'' + block.dest + '\')}" type="text/css" rel="stylesheet" />';
                },
                js: function(block) {
                    grunt.log.writeln('in js block!');
                    return '<script type="text/javascript" src="{!URLFOR($Resource.SCSClientView, \'' + block.dest + '\')}"></script>';
                }
            }
        }
    }
```

In addition, I also tried modifying the following in fileprocessor.js

var defaultBlockReplacements = {
  css: function (block) {
    var media = block.media ? ' media="' + block.media + '"' : '';
    return '<link rel="stylesheet" href="' + block.dest + '"' + media + '>';
    // I tried returning something else here.  It didn't get picked up or even called, it seems.

  },
  js: function (block) {
    var defer = block.defer ? 'defer ' : '';
    var async = block.async ? 'async ' : '';
    return '<script ' + defer + async + 'src="' + block.dest + '"><\/script>';
    // I tried returning something else here.  It didn't get picked up or even called, it seems.

  }
};

**Comment by stalsma** [comment]
Just to add on to this for future visitors, the blockReplacements does not exist in early versions of useMin.  I had to upgrade my package; then it worked w/o issue.
