### ISSUE TITLE
Usemin processing directories

### ISSUE THREAD

**Issue by FreakTheMighty** [yeoman/grunt-usemin#474]
I've bumped into an issue with a bower packaged containing ".js" in its directory name. The glob pattern I'm using `/public/{,*/}*.js'`, captures this directory and causes errors down stream. I think usemin should skip any paths that are directories.

```
Processing as JS - dist/public/bower_components/imgcache.js
Warning: EISDIR, illegal operation on a directory Use --force to continue.
Error: EISDIR, illegal operation on a directory
    at Object.fs.readSync (fs.js:481:19)
    at Object.fs.readFileSync (fs.js:315:28)
    at new module.exports (/private/tmp/gogogab/node_modules/grunt-usemin/lib/file.js:158:21)
    at FileProcessor.process (/private/tmp/gogogab/node_modules/grunt-usemin/lib/fileprocessor.js:150:17)
    at /private/tmp/gogogab/node_modules/grunt-usemin/tasks/usemin.js:132:31
    at Array.forEach (native)
    at /private/tmp/gogogab/node_modules/grunt-usemin/tasks/usemin.js:126:13
    at Array.forEach (native)
    at Object.<anonymous> (/private/tmp/gogogab/node_modules/grunt-usemin/tasks/usemin.js:124:16)
    at Object.<anonymous> (/private/tmp/gogogab/node_modules/grunt/lib/grunt/task.js:264:15)
```

**Comment by ArturT** [comment]
In my case I changed the pattern to:
```
'public/{,*/}*.js$'
```

**Comment by stephanebachelier** [comment]
@FreakTheMighty your error should be fixed with the release of usemin 2.5.1 which has been done on the 27th of october. The commit which have fixed your issue is 59676e7d and was made on the 24th of october.

@ArturT not sure if you're speaking about `usemin` or `useminPrepare` configuration.

**Comment by stephanebachelier** [comment]
Hmm I try to create a test that can show the error. I confirm from my test the referenced commit in my previous comment prevent the processing of any directory ending with `.js`. By I need to update my test to make it pass.

**Comment by ArturT** [comment]
@stephanebachelier I have excluded files in `rev` and `usemin` configuration, you can take a look. Project was generated with https://github.com/DaftMonk/generator-angular-fullstack

Here is my configuration:
https://github.com/ArturT/rubygems-tracker/blob/master/Gruntfile.js#L262
https://github.com/ArturT/rubygems-tracker/blob/master/Gruntfile.js#L239

**Comment by stephanebachelier** [comment]
@ArturT ok thanks.

**Comment by stephanebachelier** [comment]
@ArturT I've send you a PR on your project. Basically I've just upgrade usemin to v3 and switch `grunt-rev` with `grunt-filerev`.
You might need to confirm that everything works, but at least it does not break at build time.

**Comment by stephanebachelier** [comment]
Closing as upgrading to usemin v3 fixed the bug.
