### ISSUE TITLE
Different URLs for replacements

### ISSUE THREAD

**Issue by azngeek** [yeoman/grunt-usemin#484]
Hello everybody,

i primary use  statements like this for usemin:

I can not work with relative urls as i have different servers and environment with different domains/subdomains but everything is based on the same codebase. I can not explain the reason why we are not using relative urls because it is a little more complicated. My question is:

Is it possible to configurae grunt-usemin in a way, that it replaces all relative urls with absolute urls like this:

  will be converted to https://domain.tld/source/file.css

Thank you

**Comment by tomaszlukasik** [comment]
I know it might be too late, but possible solution for other people:
https://github.com/callumlocke/grunt-cdnify

**Comment by arthurvr** [comment]
I'm wondering if we really want this to be part of `grunt-usemin`. Seems like a quite specific use case, which might indeed fit better as another task.

**Comment by stephanebachelier** [comment]
@arthurvr you're right. This should be done in a different task. I've already done this before and it's quite easy by using filerev map.

**Comment by arthurvr** [comment]
@stephanebachelier So, can you close the issue?
