### ISSUE TITLE
Using the file API

### ISSUE THREAD

**Issue by jjkiesch** [yeoman/grunt-usemin#489]
I am trying to figure out a way to have usemin look at a different pattern between the build blocks. After digging through the code, I believe there is a way to do it when I found the [comment about passing in an object](https://github.com/yeoman/grunt-usemin/blob/1b5fcefc979d6c904e2957721a94c39971115633/lib/fileprocessor.js#L226).

Is there an example on how to use this in your grunt projects?

**Comment by stephanebachelier** [comment]
@jjkiesch can you elaborate ?

**Comment by stephanebachelier** [comment]
Closing for lack of response.
