### ISSUE TITLE
add a use case of using assetsDirs?

### ISSUE THREAD

**Issue by stevemao** [yeoman/grunt-usemin#498]
`assetsDirs` option can be quite confusing as it is the list of directories where we should start to look, rather than where the assets (images/fonts) are located.

**Comment by andidev** [comment]
agree

**Comment by stephanebachelier** [comment]
@stevemao take a look at my example in #517 and come back if not explicit.

**Comment by stevemao** [comment]
:+1: Not sure about the English language grammar tho. Should it be "Suppose in `index.html`" instead of "Supposed in `index.html`"?

**Comment by stephanebachelier** [comment]
@stevemao I'm not a native english speaker :) 
PR updated. Thanks for the review!
