### ISSUE TITLE
css minification is breaking all of my css

### ISSUE THREAD

**Issue by xtianus79** [yeoman/grunt-usemin#504]
There is something that is causing the css to be minified incorrectly and causing errors.  it seems as if the selector is there and then there is something else that is more adherent to the selector's class.  so this > this > that .class also comes up as .class when that was never specified before.  

in fact, after looking through it more thoroughly it is actually pretty systemic throughout.  Some errors don't show but in my case a few did.  

.footer-rsrt > section.footer-top {
padding-top: 10px;
padding-bottom: 35px;
 }

Here is the class after.... 

.footer-rsrt>section.footer-top {
padding-top: 10px;
padding-bottom: 35px;
}

along with this class designation that was never described before. Thus breaking my whole page.  

.footer-top {
padding-top: 10px;
padding-bottom: 35px;
display: inline-block; 
}

**Comment by sindresorhus** [comment]
https://github.com/jakubpawlowicz/clean-css/issues
