### ISSUE TITLE
Replace filerevved files in encoded strings.

### ISSUE THREAD

**Issue by jmalczak** [yeoman/grunt-usemin#506]
Hi 

I use grunt-usemin with jekyll to create static content for my blog. As part of it, I have feed.xml file with all of my posts joined together in XML as a RSS Atom feed. Since it is XML, all my HTML markup is encoded in XML tags. You can see an example here: https://github.com/jmalczak/jmalczak.github.io/blob/master/feed.xml. Since now grunt-usemin doesn't support replace in encoded strings I have no way to replace image URL's in my feed.xml file. For example t4toolboxInstall.jpg should be replaced with revved version. I will be more than happy to implement it, but I was wondering if I should create separate entry for xml in fileprocessor.js and put relevant patterns there or maybe you have any other preferred way of doing it. 

Thanks

**Comment by sindresorhus** [comment]
https://github.com/yeoman/grunt-usemin/pull/511#issuecomment-73463247
