### ISSUE TITLE
Usemin comments are ignored when "Mark of the Web" code is present

### ISSUE THREAD

**Issue by uriklar** [yeoman/grunt-usemin#507]
My index.html file has the [mark of the web](http://msdn.microsoft.com/en-us/library/ms537628%28v=vs.85%29.aspx) line:
```
<!-- saved from url=(0014)about:internet -->
```
Followed by an empty line (as required).

This causes the usemin comments to be ignored (they work fine without the MOTW)

Thanks! Uri

**Comment by askmatey** [comment]
Stop using that **evil** MOTW thingy.

**Comment by stephanebachelier** [comment]
@uriklar why would you want this kind of comment to be processed by usemin ? It does not follow the convention `<!-- build:[target] output -->TAGS<!-- endbuild -->`

**Comment by uriklar** [comment]
Hi @stephanebachelier, I don't want usemin to process the MOTW comment. The comment has a role of it's own that doesn't have to do with usemin. The thing is, adding this comment causes usemin to fail. Anyway, @askmatey , I've since reverted from using MOTW, but maybe this thread will be usefull for other people who do want to use MOTW + usemin.

**Comment by stephanebachelier** [comment]
@uriklar thank you for your feedback, I'll keep this issue open for documentation.

**Comment by stephanebachelier** [comment]
Closing it as it should not be used.
