### ISSUE TITLE
Usemin replaces minified css with open link tags

### ISSUE THREAD

**Issue by miki4you** [yeoman/grunt-usemin#508]
```<link />``` tags are replaced with their minified counterparts as ```<link >``` tags, making the xhtml invalid. 
This was Fixed with #103 , but the issue was recreated due to code changes.

Or is there a way to specify the closing of a link tag ? 

I think the problem lies at this line of code https://github.com/yeoman/grunt-usemin/blob/master/lib/fileprocessor.js#L110 and could be fixed easy easily

**Comment by stephanebachelier** [comment]
See https://github.com/yeoman/grunt-usemin/pull/509#issuecomment-72494408
Closing link tag is XHTML which should not be used.

**Comment by kamranzafar** [comment]
Could this be reopened? I am trying to use yeoman with Spring Boot and Thymeleaf. Where thymeleaf is based on XHTML. With this open-tags issue, I can't use it with spring boot.
