### ISSUE TITLE
Documenting some issues by creating a wiki

### ISSUE THREAD

**Issue by stephanebachelier** [yeoman/grunt-usemin#519]
I've already add a comment before to create a wiki with specific configuration as I think lots of issues are users who don't understand some tricky part of usemin. 

I've started to tag issue with label 'doc' as I plan to add specific use case in a wiki.

This issue is only here the need for the documentation.

**Comment by sindresorhus** [comment]
> users who don't understand some tricky part of usemin.

I'd rather see it made simpler than documenting tricky parts.

**Comment by stephanebachelier** [comment]
> I'd rather see it made simpler than documenting tricky parts.

@sindresorhus I agree but it might take more time to make it simpler. Documentation might helps, at first, to not be overwhelmed by issues.

**Comment by sindresorhus** [comment]
Sure, I've enabled the wiki. Go nuts.

**Comment by stephanebachelier** [comment]
@sindresorhus thanks!
