### ISSUE TITLE
Different sources attempting to write to the same destination

### ISSUE THREAD

**Issue by erguotou520** [yeoman/grunt-usemin#521]
I have css file(s) which is used in some different HTML files. I code the same blocks 
``` html
<!-- build:css css/video/history/history.css -->
<link rel="stylesheet" href="video/history/history.css" type="text/css" />
<!-- endbuild -->
```
When I run grunt target, I get this error:
```javascript
Running "useminPrepare:html" (useminPrepare) task
Warning: Different sources attempting to write to the same destination:
 {
    "dest": ".tmp\\concat\\css\\video\\history\\history.css",
    "src": [
        "WebRoot\\pages\\candidate\\video\\history\\history.css"
    ]
}
```
How can I resolve this problem?

**Comment by stevemao** [comment]
I only put index.html in `useminPrepare` for config and put all html files in `usemin` for rewrite.

**Comment by erguotou520** [comment]
@stevemao My project is not a single page app

**Comment by stephanebachelier** [comment]
@erguotou520 can you share your project or a reduced test case, it will help us track down your problem.

**Comment by stephanebachelier** [comment]
@erguotou520 if I understand you have multiple page that use the same `video/history/history.css` stylesheet and `useminPrepare` is complaining on attempting to overwrite the file with the same version.

**Comment by stevemao** [comment]
That's why I recommended to put all html files for generating configs under `useminPrepare` and put all html that need to be rewritten in `usemin`.

**Comment by erguotou520** [comment]
@stephanebachelier I have resolved this problem, but forget how...

**Comment by materliu** [comment]
the same problem here.

**Comment by stigkj** [comment]
I got this to and then solved it. It seems there is no problem if the two files are identical; only if they are different will it stop with this error.

**Comment by artuska** [comment]
I have exactly the same problem. I have 2 files: admin.html and index.html. Both of them have the same code block:

    
        // here goes bunch of JS files
    

And here is my Grunt config:

        useminPrepare: {
            options: {
                dest: 'dist',
                staging: 'tmp'
            },
            html: [
                'app/admin.html',
                'app/index.html'
            ]
        },
        usemin: {
            html: [
                'dist/index.html',
                'dist/moderation.html'
            ]
        }

**Comment by artuska** [comment]
@stevemao can you show an example?

**Comment by stephanebachelier** [comment]
@artuska have you tried the approach of @stevemao ?

**Comment by stevemao** [comment]
Same as @artuska except not putting `app/admin.html` in `useminPrepare`.

**Comment by artuska** [comment]
@stevemao Thank you, it works!

**Comment by artuska** [comment]
@stevemao I have my first application (it also uses the latest *grunt-usemin* 3.0.0 and all configs in Gruntfile.js are the same) and I do write all files in useminPrepare:

    useminPrepare: {
        options: {
            dest: 'public',
            staging: 'tmp'
        },
        html: [
            'app/assets/admin.html',
            'app/assets/application.html.erb',
            'app/assets/selection.html',
            'app/assets/stub.html.erb'
        ]
    },
    usemin: {
        html: [
            'public/admin.html',
            'public/application.html.erb',
            'public/selection.html',
            'public/stub.html.erb'
        ]
    }

... and it works like a charm, with just slightly different file names. I have no Idea how it works, there are no any errors thrown.

**Comment by stephanebachelier** [comment]
@artuska it's curious that it works... might be the fact you are in `app/assets` folder ?

If you can share a project it will be helpful :)

**Comment by artuska** [comment]
@stephanebachelier Impossible to share :( It is just a usual ROR application, and, yes, there is an `app/assets` folder.

**Comment by stephanebachelier** [comment]
@artuska I'm not a ROR dev but it should be easy to mock this :)

**Comment by Darksoulsong** [comment]
This limitation makes almost impossible to usemin a multiple page app. My application is huge and has 5 `.html` files with their own dependencies that share common deps between them. The idea is to build it in order to generate a `vendor.js` with all the third party scripts and a project-common and a  project-<sitearea>.js for each page. @stevemao 's solution is not an option for me because of that.

Any idea about how to accomplish this would be awesome.

**Comment by stevemao** [comment]
Why is it not an option? I don't think you understand my suggestion

**Comment by Darksoulsong** [comment]
@stevemao It´s not an option because if I reference `a.js` only, the scripts that will be copied, concated, minified and uglified are the ones referenced in `a.html` only. Keep in mind that my project has common and specific dependencies between files, so I need , `b.html` `c.html`, `d.html`, `e.html` dependencies to be processed as well.

**Comment by stevemao** [comment]
No, They will all be replaced but the bundle.js will only based on one of the htmls

**Comment by calidion** [comment]
show reopen this issue.

**Comment by canygt27** [comment]
You should put just your index.html file on useminPrepare. Other html files must include in usemin.

Like this;

`useminPrepare: {`
  `options: {`
    `dest: '<%= config.dist %>'`
  `},`
    `**html: '<%= config.app %>/index.html'** `
`}`

and 

` usemin: { ` 
   `options: { ` 
        `assetsDirs: [`
         ` '<%= config.dist %>',`
         ` '<%= config.dist %>/images',`
         ` '<%= config.dist %>/styles' `
       ` ] `
     ` }, `
     ` css: ['<%= config.dist %>/styles/{,*/}*.css'],`
    **`  html: ['<%= config.dist %>/*.html'] `**
   ` },`

**Comment by willi1s** [comment]
I tripped this same problem recently and thought I'd share my findings;

I found that you can have multiple html files, but the combined package files must either have unique names e.g.
a.html -> vendor_a.js
b.html -> vendor_b.js
c.html -> vendor_c.js

or, the contents of the combined package must be identical (contain the same packages)

**Comment by skylarmb** [comment]
the first comment by @stevemao worked for me, thanks

**Comment by sivaneshl** [comment]
I had the same issue and then I copied and pasted my css and js links from index.html to other html pages and it worked.
