### ISSUE TITLE
usermin remove html attributes it can't recognize

### ISSUE THREAD

**Issue by yaojingguo** [yeoman/grunt-usemin#523]
I add thymeleaf tag `th:src` to my html file:
````
<!-- build:js js/all.js -->
<script src="../../../../js/utils.js" th:src="@{/js/utils.js}"></script>
<!-- endbuild -->
````
But usemin removes the `th:src` tag.  usemin should leave html element attributes it does not recognize.

This also impacts AngularJS users, see #431.

**Comment by brunowego** [comment]
+1

**Comment by daprahamian** [comment]
:+1:

**Comment by stephanebachelier** [comment]
@yaojingguo currently working on it.

**Comment by stephanebachelier** [comment]
Ok I think I got the problem. It's related to others issues with regexp.

**Comment by stephanebachelier** [comment]
@yaojingguo @brunowego @daprahamian what's your use case ?

From this block,
```html
<!-- build:js js/all.js -->
<script src="../../../../js/utils.js" th:src="@{/js/utils.js}"></script>
<!-- endbuild -->
```

You can expect it to be changed to : 
```html
<script src="js/all.js"></script>
```

or maybe with some minification:
```html
<script src="js/all.min.js"></script>
```

If you have a block with lots of scripts we can't keep the extra attributes, as we don't know what to do.
```html
<!-- build:js js/all.js -->
<script src="foo.js" th:src="@{/js/utils.js}"></script>
<script src="bar.js" th:src="@{/js/utils.js}"></script>
<script src="baz.js" th:src="@{/js/utils.js}"></script>
<!-- endbuild -->
```


You may want to look into [blockreplacements](https://github.com/yeoman/grunt-usemin#blockreplacements) options.


I'm closing this issue. Feel free to reopen if you think it's justified.
