### ISSUE TITLE
root(options) not working for array type

### ISSUE THREAD

**Issue by harpreet86** [yeoman/grunt-usemin#529]
I am using options root to tell the root directory dynamically at run time as below

>
cssmin: {
            options: {
                root: ['.tmp', 'app/<%= yeoman.dynamicFolder']
            }
        }

but this leads to error TypeError: Arguments to path.resolve must be strings

**Comment by harpreet86** [comment]
I am using the below versions:
>
"grunt": "~0.4.1",
"grunt-contrib-cssmin": "~0.7.0",
"grunt-usemin": "~2.0.0"

**Comment by stephanebachelier** [comment]
@harpreet86 you're problem should be addressed in `grunt-contrib-cssmin` which delegate all options to [jakubpawlowicz/clean-css](https://github.com/jakubpawlowicz/clean-css#how-to-use-clean-css-programmatically).
Reading the link above, it seems the `root` option is a string.
