### ISSUE TITLE
You are not supposed to mix deferred and non-deferred scripts in one block

### ISSUE THREAD

**Issue by HadrienPierart** [yeoman/grunt-usemin#547]
Hi there,

I'm having trouble with a basic usemin configuration to have all my scripts have the defer attribute and preserve it along the build. I keep getting this error (which breaks the build of course), despite having the defer attribute on ALL my scripts. Here are the comment tags I have for this :

    
      
      
    

    
    <script defer src="gen/app/app.js"></script>
      
      
    

At first, I thought that the injected scripts from bower did not have the attribute as well, but after checking, the injected scripts are all fine.
Maybe something's wrong in the way the presence/absence of the attribute is checked ?

**Comment by HadrienPierart** [comment]
Ok I found my issue after a lot of digging and it seems that the error is on your part. I had some place else a TODO comment containing the word "defer" and it broke completely the build task of usemin, I tried with and without having defer attribute in my config and I had the error I mentionned before in both cases, independently of anything I put.

Then I realized that I had this comment in my index.html : 
    

One could argue that I should not have this comment inside my build comment tags, but I actually hadnt. It was some random place at the beginning of my file so, there should be no interaction at all.

Could you please fix this issue, I'd like to be able to put TODOs at my leisure ;)

And keep on the good work !

**Comment by stephanebachelier** [comment]
@HadrienPierart could you test the `dev` branch where there are some fixes and most important a migration to HTML parsing instead of regexps.

**Comment by arthurvr** [comment]
ping @HadrienPierart - did it work for you?

**Comment by HadrienPierart** [comment]
Hi guys,
For now I dropped the TODO and it solved the issue. I'm in a big rush right now on my app so I haven't taken the time to test with the dev build sorry. I'll try to move this up in my TODO list and keep you posted !

**Comment by HadrienPierart** [comment]
I finally found some time to retry this but I can't reproduce the bug with neither the dev nor the 3.0.0 version so I guess it's a close sentence... I really dont understand.

**Comment by arthurvr** [comment]
That's good news! I couldn't repro it myself too.

**Comment by Rorkal** [comment]
I got this exact same error myself, 
my useminPrepare and usemin tasks were pointing to "**/*.html" and the defer script was one downloaded by Bower...

**Comment by artuska** [comment]
I've got the same error. 

I have:

```
<head>
    ...

    <!-- build:css inline -->
    <link rel="stylesheet" href="/styles/critical.css">
    <!-- /build -->

    <link rel="stylesheet" href="/styles/application.css" defer>
</head>
```

Fixed by just removing `html` from the `useminPrepare` config:

Before:

```
useminPrepare: {
    options: {
        dest: 'public',
        staging: 'tmp'
    },
    html: [
        'app/assets/index.html'
    ]
}
```

After:

```
useminPrepare: {
    options: {
        dest: 'public',
        staging: 'tmp'
    }
}
```

I don't use usemin's built in stuff like `concat`, `uglify` and other tasks, the only thing I use is CSS inlining and file path replace after the `grunt-filerev`.

```
usemin: {
    options: {
        assetsDirs: ['public'],
        patterns: {
            html: [
                [/(views\/.*?\.html)/gm]
            ],
            js: [
                [/(locale\/.*?\.json)/gm],
                [/(scripts\/.*?\.js)/gm],
                [/(views\/.*?\.html)/gm],
                [/(styles\/.*?\.css)/gm]
            ]
        }
    },
    html: [
        'public/*.erb',
        'public/views/**/*.html'
    ],
    js: [
        'public/scripts/**/*.js'
    ]
}
```
