### ISSUE TITLE
Issues with files naming and filerev

### ISSUE THREAD

**Issue by ezraroi** [yeoman/grunt-usemin#552]
Lets assume I have 2 static assets (html files) in my project. File a.html and b.html.
File a has a link to file b inside of it. 
Now i ran a build and the 2 files got there name changed and everything is working fine.
Now I need to make a small change only in file b -> filerev will give a new name to file b in the next build. Because file a was not changed it will have the same name as the prev build.
Now, in the next build usemin will go to file a and will fix the link to the new file b name and everything looks fine. But not, because file a still has the same name as prev build, users will get a broken link when trying to access file b from a.

Please see the issue I opened on filerev also
[https://github.com/yeoman/grunt-filerev/issues/85](https://github.com/yeoman/grunt-filerev/issues/85)

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/gruntjs
Paste in the link to the question here so others can follow ;)

**Comment by ezraroi** [comment]
Hi,
Thanks for your answer. I don't think it is question, it is a real issue. Anyway i posted a question in stack
