### ISSUE TITLE
feature: do not output compiled files

### ISSUE THREAD

**Issue by marcobiedermann** [yeoman/grunt-usemin#553]
I have the following setup:
```
<!-- build:css css/style.css -->
  <link rel="stylesheet" href="css/red.css">
  <link rel="stylesheet" href="css/green.css">
  <link rel="stylesheet" href="css/blue.css">
<!-- endbuild -->
```
I want these files to be concatenated and minified but not rewrite the stylesheets to:
```
<link rel="stylesheet" href="css/style.css">
```
I am loading this file async via JS so I do not need this output. Would be great if I could add an optional parameter like `:remove` to the comment to prevent this.

**Comment by eddiemonge** [comment]
I am confused by what you are asking for. Could you try rephrasing or posting an example of what you want to happen?

**Comment by marcobiedermann** [comment]
```
<!-- build:css css/style.css -->
  <link rel="stylesheet" href="css/red.css">
  <link rel="stylesheet" href="css/green.css">
  <link rel="stylesheet" href="css/blue.css">
<!-- endbuild -->
```

compiles to

```
<link rel="stylesheet" href="css/style.css">
```

but I want no output in my html file at all. I just need the concatenated and minified file. The actual `css/style.css` file, not the link in the html document.

**Comment by eddiemonge** [comment]
Then you should use grunt-contrib-concat and grunt-contrib-cssmin to accomplish that goal.

**Comment by marcobiedermann** [comment]
@eddiemonge Yeah, I could do it that way, but I prefer to specify the files in my html document. Otherwise I have to into `gruntfile` every time I add a new stylesheet or script

**Comment by eddiemonge** [comment]
You are trying to use a hammer to screw in a nail. Sure it might work but it isn't going to work well or possibly even at all. If you really want to do this then you will need to research how to hack it together to work for your edge case. You could always fork the project and roll your own solution with it. Or maybe look at something like grunt-sed to strip it out. Maybe put the whole thing in another comment so the output code stays commented?
