### ISSUE TITLE
Support for Browserify

### ISSUE THREAD

**Issue by piotrkulpinski** [yeoman/grunt-usemin#557]
Hi guys,
I've noticed that there's a [config file for RequireJS](https://github.com/yeoman/grunt-usemin/blob/master/lib/config/requirejs.js) library but I can't get my browserify config to work with usemin.

Are there any plans to support that in near future?
/ Piotrek

**Comment by sindresorhus** [comment]
There's nothing to configure. You just run Browserify first, then rev the compiled file like normal.
