### ISSUE TITLE
usemin block build is not working when src attribute have space.

### ISSUE THREAD

**Issue by zeakd** [yeoman/grunt-usemin#569]
It means 

    
    <script src='my.js'></script>
    

works, but

    
    <script src ='my.js'></script>
    

or 

    
    <script src= 'my.js'></script>
    

doesn.t.

is this bug?

**Comment by sindresorhus** [comment]
Already fixed by https://github.com/yeoman/grunt-usemin/commit/39cc8c854e387d6de930e91f2ebfb49f1a9ee5d5

**Comment by zeakd** [comment]
thanks :)
