### ISSUE TITLE
really stuck after an hour on this : Cannot find module 'myapp/node_modules/grunt-usemin/lib/config/uglifyjs

### ISSUE THREAD

**Issue by landed1** [yeoman/grunt-usemin#575]
Running "useminPrepare:html" (useminPrepare) task
Warning: Cannot find module 'myapp/node_modules/grunt-usemin/lib/config/uglifyjs' Use --force to continue.

its failing here and I checked the dependencies and tried to load them on top like this 

require('load-grunt-tasks')(grunt);
grunt.loadNpmTasks('grunt-contrib-concat');
grunt.loadNpmTasks('grunt-contrib-uglify');
grunt.loadNpmTasks('grunt-contrib-cssmin');
grunt.loadNpmTasks('grunt-filerev');

I tried many things like installing locally to the project etc...

the config is like this :

```js
useminPrepare: {
            html: '<%= yeoman.app %>/index.html',
            options: {
                dest: '<%= yeoman.dist %>',
                staging: '.temp',
                flow: {
                    html: {
                        steps: {
                            js: ['concat', 'uglifyjs'],
                            css: ['cssmin']
                        },
                        post: {}
                    }
                }
            }
        },
```

**Comment by arthurvr** [comment]
Looks like an installation error. Try deleting `node_modules` and `npm install`ing again.

**Comment by landed1** [comment]
I can say if I type in 
uglifyjs
then I get a hanging situation instead of command not found so it seems to have some kind of PATH ? Or been installed but what works IS  
js: ['concat', 'uglifyjs'],     to    js: ['concat', 'uglify'],

thanks for the idea though arthurvr

**Comment by arthurvr** [comment]
> I can say if I type in 
> uglifyjs

That's unrelated to the Grunt plugin, more of a problem with your local setup.

**Comment by landed1** [comment]
yes I agree

**Comment by stephanebachelier** [comment]
probably related to #591 issue, but without knowing your version it's difficult to say.
