### ISSUE TITLE
usemin not using well formed <link> element that fails strict HTML validation

### ISSUE THREAD

**Issue by dlmiles** [yeoman/grunt-usemin#584]
When usemin replaces a <link> element it uses the form
`<link href="" rel="">`

this is not the most compatible output.  It should have a closing element sequence as well such as:

`<link href="" rel=""/>`

or

`<link href="" rel=""></link>`

Ideally maybe the default mode would be to reproduce the input form.  Thus allowing those who need to save the extra byte able to do so.  Or maybe they should just use a different tool, maybe HTMLMIN afterwards :)  one tool that does a single job well and all that.

But at the moment the output fails to validate correctly in environments where the markup is further processed by things that care and are attempting to advise the developer of potential problems.  While HTML might be liberal XHTML certainly isn't and there is no reason why this plugin should not work with all just as well.

**Comment by dlmiles** [comment]
https://github.com/yeoman/grunt-usemin/blob/master/lib/fileprocessor.js#L110

This is the line that looks like it need to single character addition.

**Comment by dlmiles** [comment]
https://github.com/yeoman/grunt-usemin/pull/585

**Comment by eddiemonge** [comment]
> The current is valid strict HTML. I guess you're trying to validate against XHTML, but that format has been moot for years.

**Comment by dlmiles** [comment]
I think you are misinformed http://www.w3.org/TR/html5/

**Comment by eddiemonge** [comment]
link is a void element meaning it doesnt need an end tag.

**Comment by dlmiles** [comment]
http://www.w3.org/TR/html5/syntax.html#void-elements

```
8.1.2.1 Start tags ... 

6 Then, if the element is one of the void elements, or if the element is a foreign element,
  then there may be a single "/" (U+002F) character. This character has no effect on
  void elements, but on foreign elements it marks the start tag as self-closing.
```

The word MAY is used, meaning it is optional.

So the real issue is if braking HTML 4.01 compatibility is a major concern.

Then even if HTML 4.01 compatibility is broken, which browsers in use today are restrictive enough in their parsing to not render pages correctly.  As in is it actually possible to use a DOCTYPE of configure a browser to be as strict as possible and get an incorrect render with any of the top 99.999% of browsers in use today.

An alternative is I can add an option to the options map for grunt-usemin so it can be specified to switch the output HTML mode and we can have HTML (using current form as now) or XHTML (to include the / character at the end of the start tag)

`
options: {
  htmlOutputMode: 'XHTML'
}
`

**Comment by eddiemonge** [comment]
> This character has no effect on void elements

Why would you not use HTML5 mode?

**Comment by dlmiles** [comment]
The final output rendered to the browser by the webserver is HTML5 not XHTML5, as indicated by content body premable / DOCTYPE and Content-Type.

However the server side template engine uses markup namespaces and a stricter validation (to help see bugs sooner in the development cycle).  This is the input for grunt-usemin.
