### ISSUE TITLE
Chalk dependency issue

### ISSUE THREAD

**Issue by alexbeletsky** [yeoman/grunt-usemin#588]
There is an issue with one of dependencies, namely chalk/chalk#81

npm published version v0.8.0 depends on "chalk": "^0.5.1" which still contains the bug and brakes current build pipeline. In master, it already fixed to "chalk": "^1.0.0".

If it can be back-ported and package is re-published, that would be just awesome.

Simialar issue in `grunt-contrib-copy` https://github.com/gruntjs/grunt-contrib-copy/issues/251

**Comment by alexbeletsky** [comment]
cc @sindresorhus if you can please process that, I would really appreciate it. :)

**Comment by sindresorhus** [comment]
Done.
