### ISSUE TITLE
Grunt usemin crash on execute task 

### ISSUE THREAD

**Issue by sergio773** [yeoman/grunt-usemin#589]
Running "useminPrepare:html" (useminPrepare) task
Warning: Cannot find module '\node_modules\grunt-usemin\lib\config\uglifyjs' Use --force to continue.

**Comment by JSlifierz** [comment]
I also experienced this. Seems as though there's a '.' missing in uglify.js...

**Comment by stephanebachelier** [comment]
@sergio773 @JSlifierz it has been renamed because it was an issue.
What version of usemin are you using ?

**Comment by stephanebachelier** [comment]
Sorry for double posting. Yes breaking change since 3.0 and due to fix post processor issue in #409.

**Comment by thematho** [comment]
Same issue here, i had to stick to "grunt-usemin": "3.0.0",

**Comment by stephanebachelier** [comment]
@thematho @sergio773 @JSlifierz this issue should be fixed with 3.1.1 soon to be released on npm.
At least there is a tag on github repo if you want to test.
