### ISSUE TITLE
lib/config/uglifyjs is missing in 3.1.0

### ISSUE THREAD

**Issue by mohsen1** [yeoman/grunt-usemin#591]
Release of 3.1.0 broke our build at [Swagger Editor](https://github.com/swagger-api/swagger-editor). Apparently `lib/config/uglifyjs'` is missing.

**Comment by SmoshySmosh** [comment]
+1 

Having the same issue.

**Comment by abramz** [comment]
+1

Having same issue.

**Comment by stephanebachelier** [comment]
@sindresorhus @arthurvr we have a breaking changing here that we need to fix. 

3.1.0 ships a breaking change where uglify flow step was renamed from `uglifyjs` to `uglify` for [name consistency](https://github.com/yeoman/grunt-usemin/issues/409#issuecomment-50111623) to fix an issue (#409), which give us : 
- `lib/task/uglify`
- `uglify` flow step

which is the same as in `grunt-contrib-uglify`, which in fact depends on ... [`uglify-js`](https://github.com/gruntjs/grunt-contrib-uglify/blob/master/package.json#L21)

How guys do you think we should resolve this issue ? Breaking change is really bad but we might have others issues about naming consistency.

At least we can revert change from [this commmit](https://github.com/yeoman/grunt-usemin/commit/748261430807582280ab99d4b12760dd1646b321) and publish a 3.2.0 version.

Another way is to support both name with a deprecation notice to encourage people to use the name `uglify` and not `uglifyjs`.

I would prefer a notice in README and a fix to support both name with a deprecation notice.

**Comment by stephanebachelier** [comment]
@sindresorhus @arthurvr I'm working on a fix that would support both naming. It should not be that hard.

**Comment by stephanebachelier** [comment]
Message added to README.

**Comment by paulclarkin** [comment]
If you revert the commit and publish 3.2.0 will uglify still work? I've changed from `uglifyjs` to `uglify` as above. Will I have to change back again?!

**Comment by paulclarkin** [comment]
As an additionally note, should this have been published as a major version update?

**Comment by brunowego** [comment]
+1

**Comment by hristozov** [comment]
This should have been published as 4.0.0. Putting this change in 3.1.0 violates semantic versioning.

**Comment by stephanebachelier** [comment]
@hristozov you're right but as we are missing maintainers this change was not seen as a breaking change (my bad).
I will publish a patch probably this evening (Europe) to support both 'uglify' and 'uglifyjs'. Need to fix some tests.

Would you agree with a 3.1.1 ? It would help anyone having this issue to update to latest.

**Comment by stephanebachelier** [comment]
@paulclarkin no you would not have to change anything with my patch. It would support both.
We need to help you guys and still be consistent with the name which should be uglify as grunt-contrib-uglify.

**Comment by rafialikhan** [comment]
Look for uglifyjs in the Gruntfile.js and renaming it to uglify worked for me.

**Comment by stephanebachelier** [comment]
@rafialikhan you're right.
Just to let you know the patch will be released today.

**Comment by stephanebachelier** [comment]
@sindresorhus @arthurvr I don't have the right to publish the new version on npm.

**Comment by takotuesday** [comment]
@stephanebachelier can you re-open this issue until the new version has been published to npm?

**Comment by arthurvr** [comment]
Done.
