### ISSUE TITLE
Usemin stops working after grunt-injector

### ISSUE THREAD

**Issue by TJNevis** [yeoman/grunt-usemin#599]
It's taken me quite a while to know exactly when grunt-usemin stops working and I finally figured out that it seems to be after grunt-injector.

On my index.html page, I have these blocks:

When I have my local and Bower dependency CSS and JS inject with grunt-injector, running grunt-usemin will not work properly - it never replaces the references on my index.html page.  The index.html page tries to load all of the files that were on the dev site, but they don't exist since the reference should update to compiled.min.css and compiled.min.js.

The odd thing is, if I open index.html and just re-save it, then re-run grunt-usemin, everything works fine.  Is there some kind of invisible character issue or something like that?  I've been able to consistently have this issue on both Windows Server 2012 and Ubuntu Linux 14.04.3 LTS.

**Comment by luxueyan** [comment]
I had been in the same trouble like you！It because the grunt injector lineendings！You can try this in injector settings
```
options: {
        lineEnding: grunt.util.linefeed
       // other options
    },
```

**Comment by TJNevis** [comment]
Awesome!  That worked.  Thanks so much for your help!

**Comment by ptitgraig** [comment]
Thanks @luxueyan this helped me a lot as well.

**Comment by TJNevis** [comment]
One thing that also helped was to convert the whole file giving you an issue, for me it was index.html.  I was still having intermittent problems, but this seems to work (along with the lineEnding option).

$  file index.html
The above command shows the line endings of the file, currently.

$  apt-get install dos2unix
$  dos2unix index.html

$  file index.html
You should see the line endings have changed

Then just commit it to Github.  Now when I pull from my skeleton repo, I haven't been having as many issues.

**Comment by ptitgraig** [comment]
Closing the issue since @TJNevis found its answer.
