### ISSUE TITLE
I need help to Drupal theme info file integration

### ISSUE THREAD

**Issue by jackncoke** [yeoman/grunt-usemin#600]
Hi guys, I have a question about theme deployment.

bower and wiredep modules works quite nicely, I add a lot of content this way! however, now I have to combine these files such as bundle.js, bundle.css etc... grunt-usemin module works very well for this purpose, but I could not find an integration for Drupal theme info file (see: https://www.drupal.org/node/171205 ) Below you can see a sample file:

    name = Theme
    description = Tableless, recolorable, multi-column, fluid width theme (default).
    version = 1.0
    core = 7.x

    ;bower:css
    stylesheets[all][] = src/components/module1/style1.css
    stylesheets[all][] = src/components/module2/style2.css
    ;endbower

    ;bower:js
    scripts[] = src/components/module/dist/vendor.js
    scripts[] = src/components/module2/dist/script.js
    ;endbower

Waiting for your help in this regard.

Thank you.

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/gruntjs
Paste in the link to the question here so others can follow ;)
