### ISSUE TITLE
Timestamp at the End of JS/CSS Files

### ISSUE THREAD

**Issue by realph** [yeoman/grunt-usemin#606]
I was wondering if it's possible to add a dynamic timestamp to the end of my file references in my `index.html` file. For example:

    <link href="style.css?v=20151120120000">
    <script src="app.js?v=20151120120000">

I don't want to rename the file, just simply change the references to the files.

I've tried to use an Angular expression in my build comment, but usemin seems to ignore that.

    

Is this at all possible. Any help is appreciated. Thanks in advance!

**Comment by eddiemonge** [comment]
usemin ignores that because it is serving the page and then running the on page javascript. It parses the page itself and looks for things it knows how to deal with.

Why do you want to add the query timestamps instead of letting filerev rename the files?

**Comment by realph** [comment]
@eddiemonge It's just a preference thing. I'd prefer to have the timestamp in the file reference to the JS and CSS files. Are you saying filerev is better placed to do such a thing?

**Comment by eddiemonge** [comment]
Yes. Query strings dont always cache defeating the purpose of it. File name versioning is a better way to cache it.

**Comment by stephanebachelier** [comment]
@realph filerev is better for caching as stated by @eddiemonge and by the way it's supported by usemin.
It's also better because filerev will generate a hash depending on the file content. If the file change the hash is changed.

Closing the issue.
