### ISSUE TITLE
question

### ISSUE THREAD

**Issue by varunprakas** [yeoman/grunt-usemin#622]
Why 'grunt-usemin' title showing as "[UNMAINTAINED] Replaces references to non-optimized scripts or stylesheets into a set of HTML files" ?

Does it means that 'grunt-usemin' no longer available?
Because i am using 'grunt-usemin' in my project

Thanks
Varun

**Comment by sindresorhus** [comment]
You're free to use it, but there's no one actively working on it.

See: https://github.com/yeoman/grunt-usemin/issues/313
