### ISSUE TITLE
"js is not defined" warning while processing template

### ISSUE THREAD

**Issue by microcosm** [yeoman/grunt-usemin#624]
I get the following output:

```
>  grunt useminPrepare
Running "useminPrepare:html" (useminPrepare) task
Warning: An error occurred while processing a template (js is not defined). Use --force to continue.
```

Here is [my template](https://github.com/Art-A-Hack/art-a-hack.github.io/blob/source/app/_layouts/default.html):

```
    <!-- build:js(app) /javascript/script.js -->
    <script src="/javascript/jquery.js"></script>
    <script src="/javascript/site.js"></script>
    <script src="/javascript/analytics.js"></script>
    <script src="/_bower_components/ideal-image-slider/ideal-image-slider.js"></script>
    <!-- endbuild -->
```

**Comment by refactornator** [comment]
It looks like @microcosm fixed this with [this commit](https://github.com/Art-A-Hack/art-a-hack.github.io/commit/65804b43ad0634686c015f3bf3cc0b63ea22e72b). It worked for me too 👍

**Comment by microcosm** [comment]
Yep, it turned out to be a Gruntfile parsing error. Once usemin rewrites config values to the Gruntfile, the Gruntfile is reloaded and parsed, producing a parsing error that doesn't show up when the Gruntfile is originally parsed.
