### ISSUE TITLE
How does it support media="screen" and other attributes?

### ISSUE THREAD

**Issue by xiaoli** [yeoman/grunt-usemin#79]
My issue right now is how to make media="screen" out.

grunt before:

``` html
<!-- build:css "/static/css/app.min.css -->
<link rel="stylesheet" href="/static/css/a.css" media="screen" />
<link rel="stylesheet" href="/static/css/b.css"  media="screen" />
<link rel="stylesheet" href="/static/css/c.css"  media="screen" />
<!-- endbuild -->
<link rel="stylesheet" href="/static/css/print.css"  media="print" />
```

grunt after:

``` html
<link rel="stylesheet" href="/static/css/app.min.css" />
<link rel="stylesheet" href="/static/css/print.css"  media="print" />
```

Thanks.

**Comment by willi1s** [comment]
I had all the same problems as I use ng-if on some css files. I've overcome it by adding a blockReplacements to my `usemin: options:` which keeps all tags as follows;

    usemin: {
      html: ['<%= yeoman.dist %>/{,*/}*.html'],
      css: ['<%= yeoman.dist %>/styles/{,*/}*.css'],
      options: {
        assetsDirs: ['<%= yeoman.dist %>','<%= yeoman.dist %>/images'],
        blockReplacements: {
          css: function(block) {
              /** find the first of the raw blocks that matches as a link, then extract the string to the left
                * and the right of the href and put the new dest path in the middle of them, the keeping any
                * attributes. Note: the attributes applied to the first link tag will be used, so if differnt
                * attributes are required for different files, they need to be in their own block */
              var result = '';
              for(var i=0; i<block.raw.length; i++) {
                  if(block.raw[i].match(/\s*<link[^\>]+href=['"][^"']+["']/gm)) {
                      result = block.raw[i].replace(/\s*(<link[^\>]+href=['"])[^"']+(["'])/gm, '$1' + block.dest + '$2');
                      break;
                  }
              }
              return result;
          }
        }
      }
    },

Hopefully the comments are clear enough to explain how it works. Hopefully it will be useful to you guys
